version: '3.4'
services:
  vite-docker:
    image: node:18-alpine
    container_name: vite-docker-container
    entrypoint: /bin/sh
    ports:
      - '8000:8000'
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true